### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by DionAkkerman** [NLDCSC/nldcsc#34]
https://github.com/NLDCSC/nldcsc/blob/bbc982c8c146a974cd05b6d49f0822fcea41aa66/nldcsc/flask_managers/flask_app_manager.py#L108

Permission error when creating INIT_COMPLETED in a docker setup. Will have to investigate a bit more - > currently created the file myself to bypass.

**Comment by P-T-I** [comment]
Maybe a mismatch between the user that’s running the docker container and the user that runs the flask manager?

**Comment by P-T-I** [comment]
@DionAkkerman is this still an issue?

**Comment by DionAkkerman** [comment]
Nope, seems to be resolved.
