### ISSUE TITLE
[Flask_sql_migrate] Connection stays open after upgrade

### ISSUE THREAD

**Issue by Thomas-Dolle** [NLDCSC/nldcsc#64]

**Comment by cyber0828** [comment]
![Screenshot from 2024-08-30 12-18-59](https://github.com/user-attachments/assets/d0cad1ba-009a-4612-b552-4fa0bbd9634b)

After running upgrade with test app.

**Comment by P-T-I** [comment]
@Thomas-Dolle That's probably just a sql lite issue; your gui is locking the sqllite database so your code cannot acces it...

**Comment by Thomas-Dolle** [comment]
This seems to be an issue regarding the snap version of DBeaver-ce. Using the deb package from the DBeaver site resolves this issue.
You can validate this by trying to create a sqlite db from scratch using DBeaver, in my case I got the same error without ever running sql_migrate functions using the snap version. The deb package version worked without issues.
