### ISSUE TITLE
[Flask_sql_migrate] db init fails db is NoneType

### ISSUE THREAD

**Issue by Thomas-Dolle** [NLDCSC/nldcsc#65]

**Comment by cyber0828** [comment]
Issue with using plugin on racoon

![Screenshot from 2024-08-30 12-18-59](https://github.com/user-attachments/assets/45dbca2b-e0ef-43a2-b7e9-d680210fffaf)

**Comment by cyber0828** [comment]
https://github.com/NLDCSC/racoon/tree/feature/test-flask-sql-migrate

**Comment by Thomas-Dolle** [comment]
Issue fixed; Moved the creation of context to be initialized in the `init_app` call instead of the `__init__` where the app and db are possibly still None.
